
name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Install docker-ce"
      run: |
        sudo apt-get update
        sudo apt-get install \
             apt-transport-https \
             ca-certificates \
             curl \
             gnupg-agent \
             software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: "Install Lando"
      run: |
        wget https://files.devwithlando.io/lando-stable.deb
        sudo dpkg -i lando-stable.deb

    - name: "Setup Env"
      run: |
        lando start
        lando setup

    - name: "Run tests"
      run: |
        lando test-unit
        lando test-wpunit
        lando test-acceptance
        lando test-functional